
export const FireBaseError = (errorCode) => {

    const errorMessages = {
        "Firebase: Error (auth/admin-restricted-operation).": "Admin only operation.",
        "Firebase: Error (auth/argument-error).": "Argument error.",
        "Firebase: Error (auth/app-not-authorized).": "App not authorized.",
        "Firebase: Error (auth/app-not-installed).": "App not installed.",
        "Firebase: Error (auth/captcha-check-failed).": "Captcha check failed.",
        "Firebase: Error (auth/code-expired).": "Code expired.",
        "Firebase: Error (auth/cordova-not-ready).": "Cordova not ready.",
        "Firebase: Error (auth/cors-unsupported).": "CORS unsupported.",
        "Firebase: Error (auth/credential-already-in-use).": "Credential already in use.",
        "Firebase: Error (auth/custom-token-mismatch).": "Credential mismatch.",
        "Firebase: Error (auth/requires-recent-login).": "Credential too old, login again.",
        "Firebase: Error (auth/dependent-sdk-initialized-before-auth).": "Dependent SDK initialized before Auth.",
        "Firebase: Error (auth/dynamic-link-not-activated).": "Dynamic link not activated.",
        "Firebase: Error (auth/email-change-needs-verification).": "Email change needs verification.",
        "Firebase: Error (auth/email-already-in-use).": "Email already in use.",
        "Firebase: Error (auth/emulator-config-failed).": "Emulator config failed.",
        "Firebase: Error (auth/expired-action-code).": "Expired action code.",
        "Firebase: Error (auth/cancelled-popup-request).": "Expired popup request.",
        "Firebase: Error (auth/internal-error).": "Internal error.",
        "Firebase: Error (auth/invalid-api-key).": "Invalid API key.",
        "Firebase: Error (auth/invalid-app-credential).": "Invalid app credential.",
        "Firebase: Error (auth/invalid-app-id).": "Invalid app ID.",
        "Firebase: Error (auth/invalid-user-token).": "Invalid Auth.",
        "Firebase: Error (auth/invalid-auth-event).": "Invalid auth event.",
        "Firebase: Error (auth/invalid-cert-hash).": "Invalid cert hash.",
        "Firebase: Error (auth/invalid-verification-code).": "Invalid code.",
        "Firebase: Error (auth/invalid-continue-uri).": "Invalid continue URI.",
        "Firebase: Error (auth/invalid-cordova-configuration).": "Invalid Cordova configuration.",
        "Firebase: Error (auth/invalid-custom-token).": "Invalid custom token.",
        "Firebase: Error (auth/invalid-dynamic-link-domain).": "Invalid dynamic link domain.",
        "Firebase: Error (auth/invalid-email).": "Invalid email.",
        "Firebase: Error (auth/invalid-emulator-scheme).": "Invalid emulator scheme.",
        "Firebase: Error (auth/invalid-credential).": "Invalid IDP response.",
        "Firebase: Error (auth/invalid-message-payload).": "Invalid message payload.",
        "Firebase: Error (auth/invalid-multi-factor-session).": "Invalid MFA session.",
        "Firebase: Error (auth/invalid-oauth-client-id).": "Invalid OAuth client ID.",
        "Firebase: Error (auth/invalid-oauth-provider).": "Invalid OAuth provider.",
        "Firebase: Error (auth/invalid-action-code).": "Invalid OOB code.",
        "Firebase: Error (auth/unauthorized-domain).": "Invalid origin.",
        "Firebase: Error (auth/wrong-password).": "Invalid password.",
        "Firebase: Error (auth/invalid-persistence-type).": "Invalid persistence.",
        "Firebase: Error (auth/invalid-phone-number).": "Invalid phone number.",
        "Firebase: Error (auth/invalid-provider-id).": "Invalid provider ID.",
        "Firebase: Error (auth/invalid-recipient-email).": "Invalid recipient email.",
        "Firebase: Error (auth/invalid-sender).": "Invalid sender.",
        "Firebase: Error (auth/invalid-verification-id).": "Invalid session info.",
        "Firebase: Error (auth/invalid-tenant-id).": "Invalid tenant ID.",
        "Firebase: Error (auth/multi-factor-info-not-found).": "MFA info not found.",
        "Firebase: Error (auth/multi-factor-auth-required).": "MFA required.",
        "Firebase: Error (auth/missing-android-pkg-name).": "Missing Android package name.",
        "Firebase: Error (auth/missing-app-credential).": "Missing app credential.",
        "Firebase: Error (auth/auth-domain-config-required).": "Missing Auth domain.",
        "Firebase: Error (auth/missing-verification-code).": "Missing code.",
        "Firebase: Error (auth/missing-continue-uri).": "Missing continue URI.",
        "Firebase: Error (auth/missing-iframe-start).": "Missing iframe start.",
        "Firebase: Error (auth/missing-ios-bundle-id).": "Missing iOS bundle ID.",
        "Firebase: Error (auth/missing-or-invalid-nonce).": "Missing or invalid nonce.",
        "Firebase: Error (auth/missing-multi-factor-info).": "Missing MFA info.",
        "Firebase: Error (auth/missing-multi-factor-session).": "Missing MFA session.",
        "Firebase: Error (auth/missing-phone-number).": "Missing phone number.",
        "Firebase: Error (auth/missing-verification-id).": "Missing session info.",
        "Firebase: Error (auth/app-deleted).": "Module destroyed.",
        "Firebase: Error (auth/account-exists-with-different-credential).": "Need confirmation.",
        "Firebase: Error (auth/network-request-failed).": "Network request failed.",
        "Firebase: Error (auth/null-user).": "Null user.",
        "Firebase: Error (auth/no-auth-event).": "No auth event.",
        "Firebase: Error (auth/no-such-provider).": "No such provider.",
        "Firebase: Error (auth/operation-not-allowed).": "Operation not allowed.",
        "Firebase: Error (auth/operation-not-supported-in-this-environment).": "Operation not supported.",
        "Firebase: Error (auth/popup-blocked).": "Popup blocked.",
        "Firebase: Error (auth/popup-closed-by-user).": "Popup closed by user.",
        "Firebase: Error (auth/provider-already-linked).": "Provider already linked.",
        "Firebase: Error (auth/quota-exceeded).": "Quota exceeded.",
        "Firebase: Error (auth/redirect-cancelled-by-user).": "Redirect cancelled by user.",
        "Firebase: Error (auth/redirect-operation-pending).": "Redirect operation pending.",
        "Firebase: Error (auth/rejected-credential).": "Rejected credential.",
        "Firebase: Error (auth/second-factor-already-in-use).": "Second factor already enrolled.",
        "Firebase: Error (auth/maximum-second-factor-count-exceeded).": "Second factor limit exceeded.",
        "Firebase: Error (auth/tenant-id-mismatch).": "Tenant ID mismatch.",
        "Firebase: Error (auth/timeout).": "Timeout.",
        "Firebase: Error (auth/user-token-expired).": "Token expired.",
        "Firebase: Error (auth/too-many-requests).": "Too many attempts, try later.",
        "Firebase: Error (auth/unauthorized-continue-uri).": "Unauthorized domain.",
        "Firebase: Error (auth/unsupported-first-factor).": "Unsupported first factor.",
        "Firebase: Error (auth/unsupported-persistence-type).": "Unsupported persistence.",
        "Firebase: Error (auth/unsupported-tenant-operation).": "Unsupported tenant operation.",
        "Firebase: Error (auth/unverified-email).": "Unverified email.",
        "Firebase: Error (auth/user-cancelled).": "User cancelled.",
        "Firebase: Error (auth/user-not-found).": "User not found.",
        "Firebase: Error (auth/user-disabled).": "User disabled.",
        "Firebase: Error (auth/user-mismatch).": "User mismatch.",
        "Firebase: Error (auth/user-signed-out).": "User signed out.",
        "Firebase: Error (auth/weak-password).": "Weak password.",
        "Firebase: Error (auth/web-storage-unsupported).": "Web storage unsupported.",
        "Firebase: Error (auth/already-initialized).": "Already initialized.",
        "Firebase: Error (auth/recaptcha-not-enabled).": "Recaptcha not enabled.",
        "Firebase: Error (auth/missing-recaptcha-token).": "Missing Recaptcha token.",
        "Firebase: Error (auth/invalid-recaptcha-token).": "Invalid Recaptcha token.",
        "Firebase: Error (auth/invalid-recaptcha-action).": "Invalid Recaptcha action.",
        "Firebase: Error (auth/missing-client-type).": "Missing client type.",
        "Firebase: Error (auth/missing-recaptcha-version).": "Missing Recaptcha version.",
        "Firebase: Error (auth/invalid-recaptcha-version).": "Invalid Recaptcha version.",
        "Firebase: Error (auth/invalid-req-type).": "Invalid request type.",
    };

    console.log(errorMessages[errorCode]);
};

